[main]
# http port for monitor and reload
httpPort=8992

# max number of CPUs to use
maxCpus = 6

# interval for get diff of proxy-state
monitorInterval = 60

# for bfe_access_pb
[PbAccessLogConf]
LogFile = /home/work/bfe/log/pb_access3.log
Modules=mod_kafka
MaxSizePerBatch = 128
