CREATE TABLE IF NOT EXISTS bfe_ai_request_log (
    hostid                  VARCHAR(256),
    log_time                DATETIME,
    ai_apikey               VARCHAR(256),
    ai_requested_model      VARCHAR(128),
    logid                   BIGINT,
    product                 VARCHAR(64),
    client_ip               VARCHAR(64),
    is_trust_src_ip         TINYINT,
    err_code                VARCHAR(64),
    err_msg                 VARCHAR(512),
    proto                   VARCHAR(16),
    header_host             VARCHAR(256),
    origin_uri              VARCHAR(2048),
    final_uri               VARCHAR(2048),
    method                  VARCHAR(16),
    content_type            VARCHAR(128),
    x_forward_for           VARCHAR(1024),
    accept_language         VARCHAR(256),
    authorization           VARCHAR(1024),
    transfer_encoding       VARCHAR(64),
    req_header_len          INT,
    req_body_len            INT,
    cluster                 VARCHAR(256),
    sub_cluster             VARCHAR(256),
    backend_info            VARCHAR(256),
    backend_retry           TINYINT,
    res_status_code         SMALLINT,
    res_header_len          INT,
    res_body_len            INT,
    res_content_type        VARCHAR(128),
    all_time                INT,
    read_client_time        INT,
    cluster_serve_time      INT,
    backend_serve_time      INT,
    write_client_time       INT,
    connect_backend_time    INT,
    proxy_delay_time        INT,
    ai_apikeytags           ARRAY<STRUCT<tagname:VARCHAR(128),tagvalue:VARCHAR(128)>>,
    ai_mapped_model         VARCHAR(128),
    ai_stream               TINYINT,
    ai_prompt_tokens        BIGINT,
    ai_output_tokens        BIGINT,
    ai_total_tokens         BIGINT,
    ai_ttft_us              BIGINT,
    ai_tpot_us              BIGINT,
    ai_rate_limit_hits      ARRAY<STRUCT<rate_limit_policy_id:VARCHAR(128),rate_limit_type:VARCHAR(32),rule_names:ARRAY<VARCHAR(128)>>>,
    ai_auth_reject_reason   VARCHAR(256),
    ai_auth_reject_quota_plans ARRAY<VARCHAR(128)>
)
UNIQUE KEY(hostid, log_time, ai_apikey, ai_requested_model)
PARTITION BY RANGE(log_time) ()
DISTRIBUTED BY HASH(ai_apikey) BUCKETS 32
PROPERTIES (
    "replication_num" = "1",
    "dynamic_partition.enable" = "true",
    "dynamic_partition.time_unit" = "DAY",
    "dynamic_partition.start" = "-7",
    "dynamic_partition.end" = "3",
    "dynamic_partition.prefix" = "p",
    "dynamic_partition.buckets" = "32",
    "compression" = "zstd"
);
