CREATE TABLE IF NOT EXISTS bfe_ai_metrics_1m (
    ts_min             DATETIME        COMMENT '分钟时间桶',
    hostid             VARCHAR(256)    COMMENT '主机标识',
    ai_apikey          VARCHAR(128)    COMMENT 'API Key',
    ai_requested_model VARCHAR(128)    COMMENT '请求模型',
    ai_mapped_model    VARCHAR(128)    COMMENT '路由模型',
    ai_stream          TINYINT         COMMENT '流式标识',
    product            VARCHAR(64)     COMMENT '产品线',
    cluster            VARCHAR(64)     COMMENT '集群',
    sub_cluster        VARCHAR(64)     COMMENT '子集群',
    backend_info       VARCHAR(256)    COMMENT '后端节点',
    method             VARCHAR(16)     COMMENT 'HTTP 方法',
    res_status_code    SMALLINT        COMMENT '响应状态码',
    err_code           VARCHAR(64)     COMMENT '错误码',
    header_host        VARCHAR(256)    COMMENT '请求 Host',
    tagslot1name       VARCHAR(128)    COMMENT '标签槽位1: tagname',
    tagslot1value      VARCHAR(128)    COMMENT '标签槽位1: tagvalue',
    tagslot2name       VARCHAR(128)    COMMENT '标签槽位2: tagname',
    tagslot2value      VARCHAR(128)    COMMENT '标签槽位2: tagvalue',
    tagslot3name       VARCHAR(128)    COMMENT '标签槽位3: tagname',
    tagslot3value      VARCHAR(128)    COMMENT '标签槽位3: tagvalue',
    tagslot4name       VARCHAR(128)    COMMENT '标签槽位4: tagname',
    tagslot4value      VARCHAR(128)    COMMENT '标签槽位4: tagvalue',
    tagslot5name       VARCHAR(128)    COMMENT '标签槽位5: tagname',
    tagslot5value      VARCHAR(128)    COMMENT '标签槽位5: tagvalue',
    rate_limit_policy_id VARCHAR(128)  COMMENT '限流策略ID',
    rate_limit_type   VARCHAR(32)     COMMENT '限流类型',
    rate_limit_rule_name VARCHAR(128)  COMMENT '限流规则名',
    ai_auth_reject_reason VARCHAR(256) COMMENT '认证拒绝原因',
    ai_auth_reject_quota_plans_slot1 VARCHAR(128) COMMENT '被拒绝配额计划槽位1',
    ai_auth_reject_quota_plans_slot2 VARCHAR(128) COMMENT '被拒绝配额计划槽位2',
    ai_auth_reject_quota_plans_slot3 VARCHAR(128) COMMENT '被拒绝配额计划槽位3',
    ai_auth_reject_quota_plans_slot4 VARCHAR(128) COMMENT '被拒绝配额计划槽位4',
    ai_auth_reject_quota_plans_slot5 VARCHAR(128) COMMENT '被拒绝配额计划槽位5',

    request_count      BIGINT   SUM    COMMENT '请求数',
    error_count        BIGINT   SUM    COMMENT '错误数',
    auth_reject_count  BIGINT   SUM    COMMENT '认证拒绝数',
    prompt_tokens      BIGINT   SUM    COMMENT '输入 Token 累计',
    output_tokens      BIGINT   SUM    COMMENT '输出 Token 累计',
    total_tokens       BIGINT   SUM    COMMENT '总 Token 累计',
    ttft_us_sum        BIGINT   SUM    COMMENT 'TTFT 累计（微秒）',
    tpot_us_sum        BIGINT   SUM    COMMENT 'TPOT 累计（微秒）',
    req_header_bytes   BIGINT   SUM    COMMENT '请求头字节累计',
    req_body_bytes     BIGINT   SUM    COMMENT '请求体字节累计',
    res_header_bytes   BIGINT   SUM    COMMENT '响应头字节累计',
    res_body_bytes     BIGINT   SUM    COMMENT '响应体字节累计',
    rate_limit_hits    BIGINT   SUM    COMMENT '限流命中次数',
    backend_retries    BIGINT   SUM    COMMENT '后端重试总次数',
    all_time_sum       BIGINT   SUM    COMMENT '总耗时累计（毫秒）',
    cluster_serve_sum  BIGINT   SUM    COMMENT '集群层耗时累计',
    backend_serve_sum  BIGINT   SUM    COMMENT '后端耗时累计'
)
AGGREGATE KEY(ts_min, hostid, ai_apikey, ai_requested_model, ai_mapped_model, ai_stream,
              product, cluster, sub_cluster, backend_info, method, res_status_code,
              err_code, header_host,
              tagslot1name, tagslot1value, tagslot2name, tagslot2value,
              tagslot3name, tagslot3value, tagslot4name, tagslot4value,
              tagslot5name, tagslot5value,
              rate_limit_policy_id, rate_limit_type, rate_limit_rule_name,
              ai_auth_reject_reason,
              ai_auth_reject_quota_plans_slot1, ai_auth_reject_quota_plans_slot2,
              ai_auth_reject_quota_plans_slot3, ai_auth_reject_quota_plans_slot4,
              ai_auth_reject_quota_plans_slot5)
PARTITION BY RANGE(ts_min) ()
DISTRIBUTED BY HASH(ai_apikey) BUCKETS 16
PROPERTIES (
    "replication_num" = "1",
    "dynamic_partition.enable" = "true",
    "dynamic_partition.time_unit" = "DAY",
    "dynamic_partition.start" = "-7",
    "dynamic_partition.end" = "3",
    "dynamic_partition.prefix" = "p",
    "dynamic_partition.buckets" = "16",
    "compression" = "zstd"
);
