CREATE JOB bfe_ai_metrics_1m_job
ON SCHEDULE EVERY 1 MINUTE
DO
INSERT INTO bfe_ai_metrics_1m
SELECT
    DATE_TRUNC(log_time, 'minute')       AS ts_min,
    COALESCE(hostid, '')                 AS hostid,
    COALESCE(ai_apikey, '')              AS ai_apikey,
    COALESCE(ai_requested_model, '')     AS ai_requested_model,
    COALESCE(ai_mapped_model, '')        AS ai_mapped_model,
    COALESCE(ai_stream, 0)               AS ai_stream,
    COALESCE(product, '')                AS product,
    COALESCE(cluster, '')                AS cluster,
    COALESCE(sub_cluster, '')            AS sub_cluster,
    COALESCE(backend_info, '')           AS backend_info,
    COALESCE(method, '')                 AS method,
    COALESCE(res_status_code, 0)         AS res_status_code,
    COALESCE(err_code, '')               AS err_code,
    COALESCE(header_host, '')            AS header_host,
    COALESCE(ELEMENT_AT(ai_apikeytags, 1).tagname, '')  AS tagslot1name,
    COALESCE(ELEMENT_AT(ai_apikeytags, 1).tagvalue, '') AS tagslot1value,
    COALESCE(ELEMENT_AT(ai_apikeytags, 2).tagname, '')  AS tagslot2name,
    COALESCE(ELEMENT_AT(ai_apikeytags, 2).tagvalue, '') AS tagslot2value,
    COALESCE(ELEMENT_AT(ai_apikeytags, 3).tagname, '')  AS tagslot3name,
    COALESCE(ELEMENT_AT(ai_apikeytags, 3).tagvalue, '') AS tagslot3value,
    COALESCE(ELEMENT_AT(ai_apikeytags, 4).tagname, '')  AS tagslot4name,
    COALESCE(ELEMENT_AT(ai_apikeytags, 4).tagvalue, '') AS tagslot4value,
    COALESCE(ELEMENT_AT(ai_apikeytags, 5).tagname, '')  AS tagslot5name,
    COALESCE(ELEMENT_AT(ai_apikeytags, 5).tagvalue, '') AS tagslot5value,
    COALESCE(ELEMENT_AT(ai_rate_limit_hits, 1).rate_limit_policy_id, '') AS rate_limit_policy_id,
    COALESCE(ELEMENT_AT(ai_rate_limit_hits, 1).rate_limit_type, '')      AS rate_limit_type,
    COALESCE(ELEMENT_AT(ELEMENT_AT(ai_rate_limit_hits, 1).rule_names, 1), '') AS rate_limit_rule_name,
    COALESCE(ai_auth_reject_reason, '')  AS ai_auth_reject_reason,
    COALESCE(ELEMENT_AT(ai_auth_reject_quota_plans, 1), '') AS ai_auth_reject_quota_plans_slot1,
    COALESCE(ELEMENT_AT(ai_auth_reject_quota_plans, 2), '') AS ai_auth_reject_quota_plans_slot2,
    COALESCE(ELEMENT_AT(ai_auth_reject_quota_plans, 3), '') AS ai_auth_reject_quota_plans_slot3,
    COALESCE(ELEMENT_AT(ai_auth_reject_quota_plans, 4), '') AS ai_auth_reject_quota_plans_slot4,
    COALESCE(ELEMENT_AT(ai_auth_reject_quota_plans, 5), '') AS ai_auth_reject_quota_plans_slot5,
    COUNT(1)                             AS request_count,
    SUM(CASE WHEN err_code != '' AND err_code IS NOT NULL THEN 1 ELSE 0 END) AS error_count,
    SUM(CASE WHEN ai_auth_reject_reason != '' AND ai_auth_reject_reason IS NOT NULL THEN 1 ELSE 0 END) AS auth_reject_count,
    SUM(COALESCE(ai_prompt_tokens, 0))   AS prompt_tokens,
    SUM(COALESCE(ai_output_tokens, 0))   AS output_tokens,
    SUM(COALESCE(ai_total_tokens, 0))    AS total_tokens,
    SUM(COALESCE(ai_ttft_us, 0))         AS ttft_us_sum,
    SUM(COALESCE(ai_tpot_us, 0))         AS tpot_us_sum,
    SUM(COALESCE(req_header_len, 0))     AS req_header_bytes,
    SUM(COALESCE(req_body_len, 0))       AS req_body_bytes,
    SUM(COALESCE(res_header_len, 0))     AS res_header_bytes,
    SUM(COALESCE(res_body_len, 0))       AS res_body_bytes,
    SUM(CASE WHEN ARRAY_SIZE(ai_rate_limit_hits) > 0 THEN 1 ELSE 0 END) AS rate_limit_hits,
    SUM(COALESCE(backend_retry, 0))      AS backend_retries,
    SUM(COALESCE(all_time, 0))           AS all_time_sum,
    SUM(COALESCE(cluster_serve_time, 0)) AS cluster_serve_sum,
    SUM(COALESCE(backend_serve_time, 0)) AS backend_serve_sum
FROM bfe_ai_request_log
WHERE log_time >= DATE_TRUNC(NOW(), 'minute') - INTERVAL 1 MINUTE
  AND log_time <  DATE_TRUNC(NOW(), 'minute')
GROUP BY ts_min, hostid, ai_apikey, ai_requested_model, ai_mapped_model, ai_stream,
         product, cluster, sub_cluster, backend_info, method, res_status_code,
         err_code, header_host,
         tagslot1name, tagslot1value, tagslot2name, tagslot2value,
         tagslot3name, tagslot3value, tagslot4name, tagslot4value,
         tagslot5name, tagslot5value,
         rate_limit_policy_id, rate_limit_type, rate_limit_rule_name,
         ai_auth_reject_reason,
         ai_auth_reject_quota_plans_slot1, ai_auth_reject_quota_plans_slot2,
         ai_auth_reject_quota_plans_slot3, ai_auth_reject_quota_plans_slot4,
         ai_auth_reject_quota_plans_slot5;
