apiVersion: 1

datasources:
  - name: Doris
    type: mysql
    access: proxy
    url: doris-fe.ai-gateway-system:9030
    database: bfe_observability
    user: root
    secureJsonData:
      password: 
    jsonData:
      maxOpenConns: 10
      maxIdleConns: 10
      connMaxLifetime: 14400
      timezone: ""
    isDefault: false
    editable: true
